version: '3.1'
services:
  stats-server:
    build: statistic/statistic_server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STATISTIC_SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/Statistic_EWM
      - SPRING_DATASOURCE_USERNAME=user
      - SPRINT_DATASOURCE_PASSWORD=password

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=Statistic_EWM
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ewm_service
    container_name: ewm_service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - EXPLORE_WITH_ME_SERVER_PORT=8080
      - STATISTIC_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/Service_EWM
      - SPRING_DATASOURCE_USERNAME=user
      - SPRINT_DATASOURCE_PASSWORD=password

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=Service_EWM
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password