DROP TABLE IF EXISTS endpointhits;

CREATE TABLE IF NOT EXISTS endpointhits(
    id integer generated by default as identity primary key,
    app varchar(50) not null,
    uri varchar(50) not null,
    ip varchar(50) not null,
    timestamp timestamp not null
);