DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS requests;

CREATE TABLE IF NOT EXISTS categories
(
    id integer generated by default as identity primary key,
    name varchar(50) not null,
    constraint category_name unique(name)
    );
CREATE TABLE IF NOT EXISTS users
(
    id integer generated by default as identity primary key,
    name varchar(50) not null,
    email varchar(50) not null,
    constraint user_email unique(email)
);
CREATE TABLE IF NOT EXISTS events
(
    id integer generated by default as identity primary key,
    title varchar(50),
    description varchar(200),
    annotation varchar(200),
    initiator integer references users (id) on delete cascade,
    category integer references categories (id) on delete cascade,
    longitude double precision,
    latitude double precision,
    event_date timestamp,
    participant_limit integer,
    created_on timestamp,
    published timestamp,
    paid bool,
    request_moderation bool,
    confirmed_requests integer,
    state integer,
    views integer
);
CREATE TABLE IF NOT EXISTS requests
(
    id integer generated by default as identity primary key,
    requester integer references users (id) on delete cascade,
    event integer references events (id) on delete cascade,
    created timestamp,
    status integer
);